aeternity/state-channel-demo

docker-compose.yml, vuejs/.eslintrc.js, vuejs/package-lock.json, vuejs/package.json, vuejs/src/App.vue, vuejs/src/components/ChannelInitialization.vue, vuejs/src/components/HelloWorld.vue, vuejs/src/sdk/sdk.ts, vuejs/tests/basic.test.ts, vuejs/tsconfig.json, vuejs/vite.config.ts
This PR creates an account for the user and connects to the channel it gets from the backend.
=> feat: initialize channel connection and connect to ws

client/package-lock.json, client/package.json, client/vite.config.ts
=> fix(client): replace commonjs import post build

.github/workflows/dev-backend.yml, .github/workflows/dev-frontend.yml, .github/workflows/prd-frontend.yml, .github/workflows/stg-frontend.yml, server/package.json, server/src/services/bot/bot.service.spec.ts, server/src/services/bot/bot.service.ts
=> feat: retry funding request when response error code is different than 425

client/src/components/ChannelInitialization.vue, client/src/components/GenericButton.vue, client/src/components/LoadingAnimation.vue, client/src/components/PopUp.vue, client/src/components/TransactionsList.vue, client/tests/channel-initialization.test.ts
Shows a loader after the user initiates the opening of the channel
=> feat: add loader

client/src/App.vue, client/src/components/ChannelInitialization.vue, client/src/sdk/sdk.ts, client/src/sdk/sdkService.ts, client/src/stores/channel.ts, client/tests/channel-initialization.test.ts, client/tests/sdk.test.ts
Move channel to App component so that it doesn't disappear when the landing page is unmounted. 🙄
=> refactor: move channel instance to App component

client/src/App.vue, client/src/components/GameInfo.vue, client/src/components/GenericButton.vue, client/src/components/Header.vue, client/src/components/PlayerInfo.vue, client/src/components/PopUp.vue, client/src/components/RockPaperScissors.vue, client/src/components/Tooltip.vue, client/src/components/TransactionsList.vue
This PR fixes some responsiveness issues on mobile devices
=> fix: responsiveness issues

docker-compose.yml, server/package-lock.json, server/package.json, server/src/route/route.interface.ts, server/src/services/bot/bot.constants.ts, server/src/services/bot/bot.interface.ts, server/src/services/bot/bot.service.spec.ts, server/src/services/bot/bot.service.ts, server/src/services/contract/contract.service.spec.ts, server/src/services/contract/contract.service.ts, server/src/services/sdk/sdk.constants.ts, server/src/services/sdk/sdk.interface.ts, server/src/services/sdk/sdk.service.ts, server/test/integration/bot.service.spec.ts, server/test/utils.ts
closes #63 
Adds jsdoc comments for server methods
Adds tests for contract methods
Updates aesdk to 12.1.1
=> Add jsdoc for server

client/package-lock.json, client/package.json, client/src/game/GameManager.ts, client/src/sdk/GameChannel.ts, client/src/sdk/sdkService.ts, client/tests/sdk.test.ts
=> Update @aeternity/aepp-sdk to 12.1.1

client/src/components/transaction/transaction.vue, client/src/utils/game-channel/game-channel.test.ts, client/src/utils/game-channel/game-channel.ts, server/src/services/bot/bot.service.ts
This PR displays both the user and the bot selection-transactions to the terminal
=> feat: display user and bot selection tx logs

client/src/components/header/header.vue, client/src/components/rock-paper-scissors/rock-paper-scissors.vue, client/src/main.ts
Clicking on the aeternity logo after having closed the channel resets the application.
=> feat: clicking logo on end-screen resets app

client/src/app.vue, client/src/components/accordion/accordion.vue, client/src/components/channel-initialization/channel-initialization.vue, client/src/components/end-screen/end-screen.vue, client/src/components/header/header.vue, client/src/components/toggle-button/toggle-button.vue, client/src/components/transaction-list/transaction-list.vue, client/src/utils/game-channel/game-channel.ts, client/src/utils/sdk-service/sdk-service.ts
In this PR we implement the autoplay feature.
=> feat: implement autoplay

client/src/components/transaction/transaction.test.ts, client/src/components/transaction/transaction.vue, client/src/utils/game-channel/game-channel.ts, client/src/utils/game-channel/game-channel.types.ts, client/tests/mocks.ts, server/src/services/bot/bot.interface.ts, server/src/services/bot/bot.service.ts, server/src/services/contract/contract.service.ts
This PR changes the wording in the transaction logs to better showcase who initiated the transaction.
=> Change wording for signed transaction

.husky/pre-push, client/package.json, server/package.json
=> revert: remove prepush testing

client/src/utils/game-channel/game-channel.test.ts, client/src/utils/game-channel/game-channel.ts
=> refactor: use node api to check if channel is open before reconnection

client/src/components/end-screen/end-screen.test.ts, client/src/components/end-screen/end-screen.vue, client/src/components/game-info/game-info.test.ts, client/src/components/game-info/game-info.vue, client/src/components/player-info/player-info.test.ts, client/src/components/player-info/player-info.vue, client/src/utils/game-channel/game-channel.ts, client/src/utils/sdk-service/sdk-service.ts
=> refactor: save results via transferFunds instead of sending an extra tx

client/src/components/share-buttons/share-buttons.vue
=> feat: update twitter sharing text

CONTRIBUTING.MD
=> Add contributing readme

client/src/components/end-screen/end-screen.vue, client/src/components/rock-paper-scissors/rock-paper-scissors.vue, client/src/utils/game-channel/game-channel.ts, server/src/route/route.spec.ts, server/src/services/bot/bot.constants.ts
=> feat: handle running out of coins

server/src/route/route.spec.ts, server/src/services/bot/bot.interface.ts, server/src/services/bot/bot.service.ts
issue  #158 have changed `runningService` to `timeStamp`
=> replace runningSince to timeStamp

client/index.html, client/src/css/game-screen/game-screen.css, client/src/css/game-screen/game-screen.scss, client/src/css/header/header.css, client/src/css/header/header.scss, client/src/css/styles.css, client/src/css/styles.scss, client/src/js/dom-manipulation/dom-manipulation.js, client/src/js/game-channel/game-channel.middleware.js
=> feat: start new round after 3 seconds and implement new game design

CHANNEL_USAGE.md, README.md
For easier reviewing, check the formatted versions:
[README.md](https://github.com/aeternity/state-channel-demo/blob/df5efe70a6d209a291412632dccf52ca63cf3343/README.md)
[CHANNEL_USAGE.md](https://github.com/aeternity/state-channel-demo/blob/df5efe70a6d209a291412632dccf52ca63cf3343/CHANNEL_USAGE.md)
=> docs: provide docs for channel usage

client/index.html, client/main.js, client/src/css/header/header.css, client/src/css/header/header.scss, client/src/css/notification/notification.css, client/src/css/notification/notification.scss, client/src/css/styles.css, client/src/css/styles.scss, client/src/css/transactions/transactions.css, client/src/css/transactions/transactions.scss, client/src/js/dom-manipulation/dom-manipulation.js, client/src/js/game-channel/game-channel.js, client/src/js/game-channel/game-channel.middleware.js, client/src/js/sdk-service/sdk-service.js, client/src/js/terminal/terminal.js, client/src/js/utils/utils.js, client/src/types/index.d.ts, server/src/services/bot/bot.service.ts, server/src/services/contract/contract.service.ts
=> feat: render logs in new terminal

client/src/js/dom-manipulation/dom-manipulation.js, client/src/js/game-channel/game-channel.js, client/src/js/game-channel/game-channel.middleware.js, client/src/types/index.d.ts
Adds an error handler - if a critical error is thrown, it is displayed in terminal
=> feat: add error handler

client/src/css/header/header.css, client/src/css/header/header.scss, client/src/css/styles.css, client/src/js/dom-manipulation/dom-manipulation.js, client/src/tests/e2e.js
=> feat: add start over button

client/src/js/dom-manipulation/dom-manipulation.js
show correct WhatsApp icon and show balance as Æ instead of æ
=> fix: correct whatsApp icon

client/src/js/dom-manipulation/dom-manipulation.js, client/src/js/game-channel/game-channel.js, client/src/js/terminal/terminal.js, server/src/route/route.spec.ts, server/src/services/bot/bot.constants.ts, server/src/services/bot/bot.interface.ts, server/src/services/bot/bot.service.ts, server/src/services/contract/contract.service.ts, server/test/mocks.ts
This PR handles ping timeouts on bot service side
=> feat: handle ping timeouts botside

client/src/css/styles.css, client/src/css/transactions/transactions.css, client/src/css/transactions/transactions.scss, client/src/js/dom-manipulation/dom-manipulation.js, client/src/js/dom-manipulation/end-screen.js, client/src/js/game-channel/game-channel.js, client/src/js/sdk-service/sdk-service.js, client/src/js/terminal/terminal.js, client/src/js/utils/utils.js, client/src/tests/e2e.js, client/src/types/index.d.ts
Display winner of every round in terminal
Display winner of game in terminal when channel closes
=> feat: display winner in terminal

.github/workflows/dev-frontend.yml, .github/workflows/stg-frontend.yml, client/.env.testnet, client/src/js/dom-manipulation/dom-manipulation.js, client/src/js/game-channel/game-channel.js, server/src/env/.env.testnet.ts
=> feat: allow user to start over after timeouts

README.md
added image and context information about state channel
=> fixed some typos and ae for æ and added content

server/package.json
see https://stackoverflow.com/questions/67063993/sh-husky-command-not-found/71242396#71242396
=> fix(server): exclude husky prepare on prd

.github/workflows/prd-backend.yml, .github/workflows/prd-frontend.yml
DO NOT MERGE YET.
It requires changes in the gitops repo and will redeploy the app, so lets sync firstly.
=> ci(build): deploy to prod on each push in main

.github/workflows/dev-frontend.yml, .github/workflows/prd-frontend.yml, .github/workflows/stg-frontend.yml
=> merge develop to main
